services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${PWD}/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d backstage -U backstage"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  server:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - internal
    volumes:
      - ${PWD}/.env:/app/.env

networks:
  internal:
    driver: bridge
