version: "3.9"
services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backstage
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

networks:
  internal:
    driver: bridge
