version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=backstage
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  server:
    depends_on:
      - db
    image: backstagefood:latest
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - internal
networks:
  internal:
    driver: bridge
