version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  server:
    build:
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - internal
    volumes:
      - ${PWD}/.env:/app/.env
networks:
  internal:
    driver: bridge
