version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage
      - POSTGRES_DB=backstage
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  server:
    build:
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - internal
    volumes:
      - ./cmd/app/.env:/app/.env
networks:
  internal:
    driver: bridge
